### ISSUE TITLE
Phone number from foreign country not understood correctly

### ISSUE THREAD

**Issue by joallard** [mobi/telephone_number#52]
I'm expecting a well-formed foreign number, even if there is a country bias, to be understood correctly. For instance, if I dial `+41446681800` in Canada, I need to understand that this is a valid Swiss number (`+41`).

```ruby
n = TelephoneNumber.parse("+41446681800", :ca)

n.valid? 
# false
# Expected: true

n.country.country_id
# "CA"
# Expected: "CH"

n.e164_number
# "41446681800"
# Expected: "+41446681800"
```

**Comment by akfernun** [comment]
Hi @joallard, 

`TelephoneNumber` strictly validates the provided number against the provided country. In this case, you asked it to validate the number against the `:ca` country code. That number is not valid in Canada, so when you ask if it is valid, the answer is `false`. Changing this functionality to what you described above would be misleading to other users of this gem. By ignoring the input country argument, one would no longer be able to determine if any particular number is valid in the specified country or not. 

If you would like `TelephoneNumber` to auto-detect the country for you (which requires you to consistently pass either the E164 or International number), then you can simply not pass  a country argument. `TelephoneNumber.parse("+41446681800")`. I hope this helps.

**Comment by joallard** [comment]
* This is not the behavior of libphonenumber.
* When confronted with a mixture of local (without prefix) and international number, that means the library doesn't have an obvious way of parsing them
* The readme does not indicate that it will completely reject any number outside the specified country

You seem to have your mind completely set though, so disregard those last points. I'll see myself out.

**Comment by akfernun** [comment]
Hi @joallard, 

I appreciate you reporting your concern. I would like to point out that this actually does conform to the default behavior of libphonenumber. Please see the example below. 

<img width="922" alt="libphonenumber_appspot_com_phonenumberparser_number_13175082437_country_ca" src="https://user-images.githubusercontent.com/5104499/36083559-b03aec3a-0f81-11e8-8e35-36b01bdd3147.png">

If we were to change the functionality that this gem provides, how would one be able to determine if a number is in fact valid for a specified region? So in the example that you provided, if the gem returned `true` for `valid?` because it is valid in Switzerland but not Canada, how would one ask if the number is strictly valid in Canada? The proposed changes remove that functionality. 

For your second point, I would like to point out that it is in fact not possible to parse a local phone number without knowing the country. Take the US number "3175082238". Without specifying a country, how would the gem know what country to validate against? Maybe the number is valid in one country but not another. And for what it's worth, pretty much any reasonable local number is valid somewhere in the world.

**Comment by joallard** [comment]
Here's another example: [`+41445583410, :CA`](https://libphonenumber.appspot.com/phonenumberparser?number=%2B41445583410&country=CA)

> So in the example that you provided, if the gem returned true for valid? because it is valid in Switzerland but not Canada, how would one ask if the number is strictly valid in Canada? The proposed changes remove that functionality.

Your screenshot seems to be making that point quite well. `valid?` true, `valid_for_region?` false. That's exactly what libphonenumber reports.

> For your second point, I would like to point out that it is in fact not possible to parse a local phone number without knowing the country. Take the US number "3175082238". Without specifying a country, how would the gem know what country to validate against?

I'm saying in the case where the number is prefixed with `+` or an IDD (eg `011` in CA). Basically, the way the local phone system would interpret it. (and pretty much the way it is reasonable to interpret within that locale) 

I don't expect a foreign phone number to be correctly parsed without an international prefix. (and by foreign, I mean in a different numbering plan. See an example of [dialing San Diego, CA, US from Canada](https://libphonenumber.appspot.com/phonenumberparser?number=18582306315&country=CA), which is of course within-NANP.)

**Comment by srpouyet** [comment]
This is an old issue, but I just wanted to say I agree with @joallard. As a workaround I set the `country_code` argument of `TelephoneNumber.parse` to `nil` if the number starts with `+`.

Also as mentioned above it doesn't seem to handle international prefixes like `00` (Netherlands) or `011` (US), is this correct? My workaround is to lookup the international prefix with `TelephoneNumber::Country.find('US').international_prefix` and replace it with `+`, which I'd expect `telephone_number` to do. Maybe I'm missing something?
