### ISSUE TITLE
Is it possible to get a user-friendly format string suitable for displaying to the user?

### ISSUE THREAD

**Issue by ksouthworth** [mobi/telephone_number#82]
The validations in this gem are great!  I'm wondering if it's possible to get a user-friendly format string out somehow that is suitable for displaying to end users, in a form input placeholder or hint, for example?  That would really make it shine.

Example for the US (United States):
"(xxx) xxx-xxxx"

Something like that would be awesome, because then we could pipe it into a client-side Javascript library to validate the format on the client-side as well, and give the user hints about the acceptable format for their country.

Thanks for a great gem!

**Comment by akfernun** [comment]
Hey @ksouthworth!

Have you checked out [this method](https://github.com/mobi/telephone_number#national_numberformatted-true)?

**Comment by ksouthworth** [comment]
Yes I've seen that formatter method, but that only works when we already have a phone number, correct?  In this case I don't know the phone # or country code yet on the front end, until the user submits the form/page.

**Comment by akfernun** [comment]
@ksouthworth, I see now. That makes sense. I'm not sure that it's something we'll be able to do. Here's why: 

Phone number validation/formatting in North America is pretty straight-forward because we really only have 1 standard format that we abide by. For example, we know that all phone numbers will be 10 digits long which makes providing a formatting "hint" easy. The problem is that other countries don't have simple rules like this. Phone numbers within a single country can be of varying lengths and some of the formats are entirely dependent on the phone number itself. This means we wouldn't really be talking about a _single_ hint, but rather many different hints (or formats) that the input _could_ abide by. 

If you don't know the formatting or the country code yet, there really are an infinite number of hints that we could provide. 

Does that clear things up?

**Comment by ksouthworth** [comment]
Yes that makes sense.  If we knew the country code ahead of time, would that narrow the list of possible hints down to a reasonable number (1 to 3) you think?

If we knew the Country Code when the page loaded, could possibly show a hint (or 2) that way...?

**Comment by akfernun** [comment]
Hey @ksouthworth, 

Unfortunately, I don't think it's going to be something we'll be able to support. Because countries can support many different formats, we won't be able to narrow it down to just one or two. Additionally, formatting rules are generally with regex, so extract hints from regex would be a pretty difficult task.

**Comment by ksouthworth** [comment]
Ok, thanks for considering it, and thanks for this gem!
